schema_version = "1.0.0"

id = "pinerig_hand_macro"
version = "1.0.0"
name = "Pinerig Hand Macro"
tagline = "Generate a hand macro bone for FK finger"
maintainer = "Enip-OIXth"
type = "add-on"

blender_version_min = "4.2.0"
license = ["SPDX:GPL-3.0-or-later"]


website = "https://github.com/Enip-OIXth/Pinerig-Hand-Macro"
support = "https://github.com/Enip-OIXth/Pinerig-Hand-Macro/issues"
tags = ["Rigging", "Animation"]
platforms = ["windows-x64", "macos-arm64", "linux-x64"]

[build]
#paths = []
paths_exclude_pattern = [
   "__dev__/",
   "__pycache__/",
   "/.git/",
   "/.github/",
   "/*.zip",
]
